# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_produtos_safra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinhaServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('custo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_produtos_safra.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_produtos_safra.Safra')),
            ],
        ),
        migrations.AddField(
            model_name='linhaservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_servicos.Servico'),
        ),
    ]
